[package]
name = "bevy_keymapper"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", default-features = false, features = ["bevy_log"] }

[dev-dependencies]
bevy = { version = "0.17.3", default-features = true }
